# Generated by Django 3.1.7 on 2021-04-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
                ('weight', models.CharField(max_length=300)),
                ('flavour', models.CharField(max_length=300)),
                ('pr', models.CharField(max_length=300)),
                ('pemail', models.CharField(max_length=300)),
                ('pphone', models.CharField(max_length=300)),
            ],
        ),
    ]
